// The following directive is necessary to make the package coherent:

//go:build ignore

// This program generates buildinfo.go. It can be invoked by running
// go generate
package main

import (
	"errors"
	"fmt"
	"io"
	"log"
	"os"
	"text/template"
	"integral/config"

	"github.com/go-git/go-git/v6"
	"github.com/invopop/jsonschema"
)

const buildFile = "buildinfo.go"
const schemaFile = "share/integral/schema.json"

func main() {
	bFile, err := os.Create(buildFile)
	if err != nil {
		log.Fatal(err)
	}
	defer bFile.Close()

	var hash, tag string
	if len(os.Args) < 2 {
		cwd, err := os.Getwd()
		if err != nil {
			log.Fatal(err)
		}
		repo, err := git.PlainOpen(cwd)
		if err != nil {
			log.Fatal(err)
		}
		head, err := repo.Head()
		if err != nil {
			log.Fatal(err)
		}
		tags, err := repo.Tags()
		if err != nil {
			log.Fatal(err)
		}
		tagRef, err := tags.Next()
		if err == nil {
			tag = tagRef.Name().Short()
		} else if errors.Is(err, io.EOF) {
			tag = "unset"
		}
		hash = head.Hash().String()
	} else {
		hash = os.Args[1]
		tag = os.Args[2]
	}

	fmt.Printf("Commit: %s\nTag: %s\n", hash, tag)
	
	temp.Execute(bFile, buildinfo{
		Commit: hash,
		Tag: tag,
	})

	jFile, err := os.Create(schemaFile)
	if err != nil {
		log.Fatal(err)
	}
	defer jFile.Close()

	schema, err := jsonschema.Reflect(&config.PromptConfig{}).MarshalJSON()
	if err != nil {
		log.Fatal(err)
	}
	jFile.Write(schema)
}

var temp = template.Must(template.New("").Parse(`// Code generated by go generate; DO NOT EDIT.
package main

const Commit = "{{ .Commit }}"
const Version = "{{ .Tag }}"
`))

type buildinfo struct {
	Commit string
	Tag string
}

