#!/usr/bin/env zsh

if [[ $1 = "benchmark" ]]; then
  go build
  hyperfine "./integral 1" -iN --export-json benchmark.json
  if [[ $(jq -r '.results.[].mean' benchmark.json) < 0.05 ]]; then
    print -P "%F{2}Pass!%f"
  else
    print -P "%F{1}Fail!%f"
  fi
elif [[ $1 = "debug" ]]; then
  go build -gcflags="all=-N -l"
  ./integral render raw ${2:-20} ${3:-0} ${4:-0} &
  pid=$!
  kill -STOP $pid
  dlv attach $pid & kill -CONT $pid
else
  go run . render raw $COLUMNS 1 0
  export SSH_CONNECTION=asdf
  go run . render raw $COLUMNS 2 1
  export CONTAINER_ID=debian
  go run . render raw $COLUMNS 126 2
fi

