#!/usr/bin/env zsh

if [[ $1 = "benchmark" ]]; then
  go build
  hyperfine "./integral 1" -iN --export-json benchmark.json
  if [[ $(jq -r '.results.[].mean' benchmark.json) < 0.05 ]]; then
    print -P "%F{2}Pass!%f"
  else
    print -P "%F{1}Fail!%f"
  fi
else
  go run *.go render raw 1 0
  export SSH_CONNECTION=asdf
  go run *.go render raw 2 1
  export CONTAINER_ID=debian
  go run *.go render raw 126 2
fi

