#!/usr/bin/env zsh

if [[ $1 = "benchmark" ]]; then
  go build
  hyperfine "./integral 1" -iN --export-json benchmark.json
  if [[ $(jq -r '.results.[].mean' benchmark.json) < 0.05 ]]; then
    print -P "%F{2}Pass!%f"
  else
    print -P "%F{1}Fail!%f"
  fi
else
  export SSH_CONNECTION=asdf
  export DIRENV_DIR=$PWD
  export CONTAINER_ID=debian
  IFS=$'\n'
  print -lP $(go run *.go 1 3)
fi

